services:
  postgres:
    image: postgres:16-alpine
    container_name: katrix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: katrix_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - npm_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: katrix-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PORT: "5000"
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET:-katrix_secret_key_change_me}
      DB_USER: postgres
      DB_PASSWORD: postgrespassword
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: katrix_db
      TZ: America/Argentina/Buenos_Aires
    networks:
      - npm_network

  katrix_pos_web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: katrix_pos_web
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    environment:
      - TZ=America/Argentina/Buenos_Aires
    networks:
      - npm_network

volumes:
  postgres_data:
    driver: local

networks:
  npm_network:
    external: true
